### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by Outstep** [araufdogan/search#1]
Hello,

I wanted to test out your metasearch engine.

How to start it locally on my Ubuntu 18.04 system?

Also, in looking at the code, I am wondering if it needs a Redis server as well?
Thanks,

**Comment by araufdogan** [comment]
Yes, redis server required. This project uses redis for session store, you can check app.js. You don't need another things. (The Freebase API has been shut-down) 
Just clone this repo, install node and redis. 
Play with `node app.js`

This is old project. I don't continue to support this project so you should edit, fix some things if necessary.
